### ISSUE TITLE
broken frontend UI

### ISSUE THREAD

**Issue by mxc1868** [Vilsol/timeless-jewels#4]
![image](https://user-images.githubusercontent.com/20630838/212189535-27ad9954-9abc-4739-b618-d52bc44b3ba9.png)

**Comment by mxc1868** [comment]
@Vilsol

**Comment by Vilsol** [comment]
Should be fixed now

**Comment by mxc1868** [comment]
@Vilsol The stats selection feature is still broken. See snapshot
![image](https://user-images.githubusercontent.com/20630838/212198234-cf22a91e-c0f2-40f5-afa2-0e8368458638.png)
